### ISSUE TITLE
A question about algorithms

### ISSUE THREAD

**Issue by Vayne0227** [neuromorphic-paris/event_batch#1]
Hello author, I have been reading your paper on this project recently. I would like to ask where is the code for this algorithm located? I am not very familiar with C++.
![8a50ad98a5528e3fb85691cf10d7804](https://github.com/neuromorphic-paris/event_batch/assets/66624169/4f67cca6-7e02-40f2-abbe-05a531261d9d)

**Comment by umgnunes** [comment]
Hello, thanks for your interest.
The core algorithm is implemented in [this method](https://github.com/neuromorphic-paris/event_batch/blob/e00db6608bc579eed13c80c50ae9b879eb875570/include/event_batch/global_decay.hpp#L136).

**Comment by Vayne0227** [comment]
Thank you very much for your help.
